# Generated by Django 5.0 on 2023-12-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_blogpage_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=models.TextField(),
        ),
    ]
