# Generated by Django 5.0 on 2023-12-11 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_blogpage_body'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPage',
        ),
    ]
