# Generated by Django 5.0 on 2023-12-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_blogpage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='sub_title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
